name       : ppsspp
version    : 1.6.3
release    : 4
source     :
    - git|https://github.com/hrydgard/ppsspp : v1.6.3
license    :
    - GPL-2.0-or-later
    - BSD-3-Clause
component  : games.emulator
summary    : PSP emulator
description: |
    A fast and portable PSP emulator
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(sdl2)
    - snappy-devel
setup      : |
    %cmake -DUSE_SYSTEM_FFMPEG=1 .
build      : |
    %make
install    : |
    install -D -m 00644 icons/icon-512.svg $installdir/usr/share/pixmaps/ppsspp.svg

    install -d $installdir/usr/share/ppsspp
    cp -dr --no-preserve='ownership' assets $installdir/usr/share/ppsspp

    install -D -m 00755 PPSSPPSDL $installdir/usr/bin/ppsspp
    install -D -m 00644 $pkgfiles/ppsspp.desktop $installdir/usr/share/applications/ppsspp.desktop
