name       : ppsspp
version    : 1.10.0
release    : 14
source     :
    - git|https://github.com/hrydgard/ppsspp.git : v1.10
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : games.emulator
summary    : PSP emulator
description: |
    A fast and portable PSP emulator
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - snappy-devel
setup      : |
    %cmake_ninja -DUSE_SYSTEM_LIBZIP=ON \
                 -DUSE_SYSTEM_SNAPPY=ON
build      : |
    %ninja_build
install    : |
    install -Dm00644 icons/icon-512.svg $installdir/usr/share/pixmaps/ppsspp.svg

    install -d $installdir/usr/share/ppsspp
    cp -dr --no-preserve='ownership' assets $installdir/usr/share/ppsspp

    install -Dm00755 solusBuildDir/PPSSPPSDL $installdir/usr/bin/ppsspp
    install -Dm00644 $pkgfiles/ppsspp.desktop $installdir/usr/share/applications/ppsspp.desktop
