name       : ppsspp
version    : 1.16
release    : 32
source     :
    - git|https://github.com/hrydgard/ppsspp.git : v1.16
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : games.emulator
homepage   : https://www.ppsspp.org
summary    : PSP emulator
description: |
    A fast and portable PSP emulator
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(libzstd)
    - pkgconfig(miniupnpc)
    - pkgconfig(sdl2)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - snappy-devel
setup      : |
    %cmake_ninja \
        -DUSE_SYSTEM_LIBZIP=ON \
        -DUSE_SYSTEM_MINIUPNPC=ON \
        -DUSE_SYSTEM_SNAPPY=ON \
        -DUSE_SYSTEM_ZSTD=ON \
        -DUSE_WAYLAND_WSI=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -s /usr/bin/PPSSPPSDL $installdir/usr/bin/ppsspp
