name       : ppsspp
version    : 1.4
release    : 2
source     :
    - git|https://github.com/hrydgard/ppsspp : v1.4
license    :
    - GPL-2.0
    - BSD-3-Clause
component  : games.emulator
summary    : PSP emulator
description: |
    PSP emulator
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(sdl2)
    - snappy-devel
setup      : |
    %cmake -DUSE_SYSTEM_FFMPEG=1 .
build      : |
    %make
install    : |
    for i in 16 24 32 48 64 96 128 256 512; do
        install -D -m 00644 icons/hicolor/"$i"x"$i"/apps/ppsspp.png $installdir/usr/share/icons/hicolor/"$i"x"$i"/apps/ppsspp.png;
    done

    install -d $installdir/usr/share/ppsspp
    cp -dr --no-preserve='ownership' assets $installdir/usr/share/ppsspp

    install -D -m 00755 PPSSPPSDL $installdir/usr/bin/ppsspp
    install -D -m 00644 $pkgfiles/ppsspp.desktop $installdir/usr/share/applications/ppsspp.desktop
