name       : ppsspp
version    : 1.14.4
release    : 29
source     :
    - https://github.com/hrydgard/ppsspp/releases/download/v1.14.4/ppsspp-1.14.4.tar.xz : 54ede41af569116d9c284f7b157d1449dcd13944675e60c2875bf3a3994f5dda
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : games.emulator
homepage   : https://www.ppsspp.org
summary    : PSP emulator
description: |
    A fast and portable PSP emulator
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(libzstd)
    - pkgconfig(miniupnpc)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - snappy-devel
setup      : |
    %cmake_ninja \
        -DUSE_SYSTEM_FFMPEG=ON \
        -DUSE_SYSTEM_LIBZIP=ON \
        -DUSE_SYSTEM_MINIUPNPC=ON \
        -DUSE_SYSTEM_SNAPPY=ON \
        -DUSE_SYSTEM_ZSTD=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -s /usr/bin/PPSSPPSDL $installdir/usr/bin/ppsspp
